### ISSUE TITLE
is there a quick start manual? 

### ISSUE THREAD

**Issue by leonall** [BorgwardtLab/maldi_amr#2]
Firstly, appreciation for your large and detailed amount of work. I am excited after reading the paper about your research findings. 

When I tried to run it, I encountered some difficulties.

**How to run the code  corresponding wih the paper? Is there a quick start manual?** 

Too many code, i don't know how to run it.

For example, i can't find `plot_fig4_curves_per_species_and_antibiotic_2panels.py`?

**Comment by Pseudomanifold** [comment]
There's no quick start manual, but all the relevant choice can be found in the subfolders. We slightly renamed some of the scripts; all plotting information can be found in the ”plotting" folder.
